# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2025 Hyperpolymath
apiVersion: v1
kind: Namespace
metadata:
  name: zerotier-system
  labels:
    app.kubernetes.io/name: zerotier
    app.kubernetes.io/part-of: flatracoon-netstack
